### ISSUE TITLE
Job dispatch

### ISSUE THREAD

**Issue by eosW** [endofsamsara/CMPS242#2]
The requirement of next submission has been posted: https://piazza.com/class/itdcdg3ucsi3xq?cid=40
Basically, it requires us to have a runnable version of our program and be able to describe our model in math.
So, here is how I plan to make it:
@yaxu75 will continuous develop bag-of-word feature and then develop word cluster feature http://www.cs.cmu.edu/~ark/TweetNLP/#resources using TF/IDF as well. Please respond so I know you read this.

And for the rest three of us, one will develop sentiment lexicons feature, thus, grading each word with a score using 3rd party dictionary (NRC, MPQA, and more) and derivative some features from it, which depends on both our data and the sentiment dictionary like:
- score of the most positive/negative words
- percentage of positive/negative words
- overall average score
- median score
- and any other feature you think is proper

The other two, will work together to learn the model of SVM Regressor, implement the most fundamental version of it, write the mathematical description, and possible teach it to the rest two members in the future.

So, for @wangweizi and @Hannabrahman you guys, please respond for what job you want, and I`ll take the rest one.

Lastly, DDL is moved Nov. 8th, but we still needs to start work early!

**Comment by fabrahman** [comment]
Thx Ruimin,
I am studying about the SVM classification. 
After that, I am going to start how SVM regressor works.
Do you suggest I just go through the LibSVM instead? Are we going to use LibSVM for doing prediction in our model?

**Comment by wangweizi** [comment]
The professor said no library is allowed when implementing the model. I am
still reading the text.

**Comment by fabrahman** [comment]
I dont think so,

Who said that?

**Comment by wangweizi** [comment]
Double check the project description. I am not sure...I think Ruimin said
it and I also have vague memory that the professor said it too, In the
first class, and some other students asked what can use and what can't.
Since I don't know Phyton libraries well, so I am not sure

C U Monday

Good night!

**Comment by fabrahman** [comment]
Actually I did not read the text book, I am just searching for online
sources. Cause it is more easier.
I am not really comfortable with txtboook.
How did u find it? is it useful?

**Comment by wangweizi** [comment]
The textbook is not easy to understand....

2016-10-30 0:29 GMT-07:00 Hannabrahman notifications@github.com:

**Comment by eosW** [comment]
I asked the TA about the usage of libraries, and it turns out that we can use third party libraries ONLY in pre-processing and data visualization part (thus, tokenize, normalize, and plotting in the future). So we have to write our own SVM.

**Comment by wangweizi** [comment]
please help me check on the attachment and see if it is a good reference
for our SVM model using sequential minimal optimization algorithm.

I found it from the link in the answer of
http://stackoverflow.com/questions/27501444/implementation-of-svm-for-classification-without-library-in-c

2016-10-30 18:15 GMT-07:00 Ruimin Ray Wang notifications@github.com:

**Comment by eosW** [comment]
If you mean to ask me, I don't know. I`ve never learned this in detail

2016-10-30 22:44 GMT-07:00 wangweizi notifications@github.com:
